@startuml SystemContext
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "User", "Interacts with the system via REST APIs")
System_Boundary(cncrud, "cn-crud-app") {
    Container(commander, "Commander", "REST entry point for create, update and delete requests")
    Container(resourceId, "ResourceID", "Generates certified buckets of unique identifiers for resources")
    Container(resourceManager, "ResourceManager", "DAPR Actor implementing business logic for resources")
    Container(resourceProjector, "ResourceProjector", "Creates materialized views from events")
    Container(cerbos, "Cerbos", "Policy Decision Point")
}

Rel(user, commander, "Manages resources")
Rel(commander, resourceId, "Requests IDs")
Rel(commander, resourceManager, "Sends commands")
Rel(resourceManager, resourceProjector, "Publishes events")
Rel(resourceManager, cerbos, "Authorization query")

SHOW_LEGEND()
@enduml

@startuml CreateResource
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

Person(user, "User")
Container(envoy, "Envoy Proxy")
Container(commander, "Commander")
Container(resourceManager, "ResourceManager")
Container(cerbos, "Cerbos")
Container(resourceProjector, "ResourceProjector")

Rel(user, envoy, "POST /resources")
Rel(envoy, commander, "Forward request")
Rel(commander, resourceManager, "Invoke createResource")
Rel(resourceManager, cerbos, "Check policy")
Rel(cerbos, resourceManager, "Allow or deny")
Rel(resourceManager, resourceProjector, "Publish event")

SHOW_LEGEND()
@enduml

@startuml CommanderRequestsUniqueIDs
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Dynamic.puml

Person(user, "User")
Container(commander, "Commander")
Container(resourceId, "ResourceID")
Container(resourceManager, "ResourceManager")

Rel(user, commander, "Requests creation")
Rel(commander, resourceId, "Asks for ID bucket")
Rel(resourceId, commander, "Returns ID bucket")
Rel(commander, resourceManager, "Creates resource")

SHOW_LEGEND()
@enduml
